---
sidebar: sidebar
permalink: ffm-dataip-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: ffm.dataip events
---

= ffm.dataip events
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== ffm.dataip.failedToHost
*Severity*::
NOTICE
*Description*::
This message occurs when a data IP address was failed to host on the node. Data access through this IP address is not available.
*Corrective Action*::
(None).
*Syslog Message*::
Data IP address %s was failed to host by the NFS protocol service on the node %s (ID: %u).
*Parameters*::
*dataip* (STRING): The IP address that was failed to host.
*nodename* (STRING): Name of the node on which the data IP was failed to host.
*nodeid* (INT): Unique identifier of the node on which the data IP was failed to host.

== ffm.dataip.successfullyHosted
*Severity*::
NOTICE
*Description*::
This message occurs when a data IP address was successfully hosted on the node. Data access through this IP address is now available.
*Corrective Action*::
(None).
*Syslog Message*::
Data IP address %s was hosted by the NFS protocol service on the node %s (ID: %u).
*Parameters*::
*dataip* (STRING): The IP address that was hosted.
*nodename* (STRING): Name of the node on which the data IP was hosted.
*nodeid* (INT): Unique identifier of the node on which the data IP was hosted.
