---
sidebar: sidebar
permalink: smbc-aufo-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: smbc.aufo events
---

= smbc.aufo events
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== smbc.aufo.completed
*Severity*::
NOTICE
*Description*::
This message occurs when the SnapMirror(R) Business Continuity (SMBC) automatic unplanned failover operation completes.
*Corrective Action*::
(None).
*Syslog Message*::
SnapMirror automatic failover completed. Destination path: %s.
*Parameters*::
*dstpath* (STRING): Path name of the destination group of the SMBC relationship.

== smbc.aufo.failed
*Severity*::
ERROR
*Description*::
This message occurs when the SnapMirror(R) Business Continuity (SMBC) automatic unplanned failover operation fails.
*Corrective Action*::
Perform "snapmirror delete -destination-path destination_path" followed by "snapmirror break" on the volumes.
*Syslog Message*::
SnapMirror automatic failover failed. Destination path: %s.
*Parameters*::
*dstpath* (STRING): Path name of the destination group of the SMBC relationship.

== smbc.aufo.failover.incapable
*Severity*::
ERROR
*Description*::
This message occurs when the SnapMirror(R) Business Continuity (SMBC) automatic unplanned failover operation fails because the destination site is not failover capable.
*Corrective Action*::
Before applying corrective action, the User must ensure that the primary/master copy is unavailable, otherwise the assumption is that Master copy is actively being used by the Application workload. Perform "snapmirror delete -destination-path destination_path" followed by "snapmirror break" on the volumes.
*Syslog Message*::
SnapMirror automatic failover encountered a failure because the site with destination path "%s" is not failover-capable.
*Parameters*::
*dstpath* (STRING): Path name of the destination group of the SMBC relationship.

== smbc.aufo.queued
*Severity*::
NOTICE
*Description*::
This message occurs when the SnapMirror(R) Business Continuity (SMBC) automatic unplanned failover operation is queued.
*Corrective Action*::
(None).
*Syslog Message*::
SnapMirror Business Continuity (SMBC) automatic unplanned operation failover queued. Destination path: %s.
*Parameters*::
*dstpath* (STRING): Path name of the destination group of the SMBC relationship.

== smbc.aufo.start
*Severity*::
NOTICE
*Description*::
This message occurs when the SnapMirror(R) Business Continuity (SMBC) automatic unplanned failover operation starts.
*Corrective Action*::
(None).
*Syslog Message*::
SnapMirror automatic failover started. Destination path: %s.
*Parameters*::
*dstpath* (STRING): Path name of the destination group of the SMBC relationship.
